# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/middleman
image: ruby:2.3

variables:
  AWS_S3_STAGING: "grp-hosted/sensoratlas/staging"
  AWS_S3_PRODUCTION: "grp-hosted/sensoratlas/production"
  AWS_CF_STAGING: "E107YMMML3LC9F"
  AWS_CF_PRODUCTION: "E1OKGBK08CT9HP"

stages:
  - build
  - deploy

cache:
  paths:
  - vendor
  - public

build:
  stage: build
  script:
  - export LC_ALL=C.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US.UTF-8
  - apt-get update -yqqq
  - apt-get install -y nodejs
  - bundle install --path vendor
  - bundle exec middleman build --build-dir=public --clean

staging:
  stage: deploy
  image: python:latest
  script:
  - apt-get update -yqqq
  - pip install awscli
  - aws s3 sync --sse --delete public s3://$AWS_S3_STAGING/ --acl public-read
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $AWS_CF_STAGING --paths '/*'
  environment:
    name: staging
  only:
  - develop

production:
  stage: deploy
  image: python:latest
  script:
  - apt-get update -yqqq
  - pip install awscli
  - aws s3 sync --sse --delete public s3://$AWS_S3_PRODUCTION/ --acl public-read
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $AWS_CF_PRODUCTION --paths '/*'
  environment:
    name: production
  only:
  - master
  when: manual
